naboj-org/bullet

bullet/problems/logic/__init__.py, bullet/problems/logic/results.py
`results-fix` as in fixing the results, we are not fixing any problem.
=> Add method to mark problem unsolved

bullet/competitions/factories/competition.py, bullet/competitions/factories/generate.py, bullet/competitions/management/commands/generatedata.py, bullet/countries/factories/generate.py, bullet/dev_setup.sh, bullet/education/factories/generate.py
=> Revert "Factories"

bullet/bullet_admin/access.py, bullet/bullet_admin/forms/category.py, bullet/bullet_admin/forms/competition.py, bullet/bullet_admin/templates/bullet_admin/categories/list.html, bullet/bullet_admin/templates/bullet_admin/competition_switch.html, bullet/bullet_admin/templatetags/badmin.py, bullet/bullet_admin/urls.py, bullet/bullet_admin/views/__init__.py, bullet/bullet_admin/views/category.py, bullet/bullet_admin/views/competition.py, bullet/competitions/templates/register/partials/competition.html, bullet/web/templates/form/field.html, bullet/web/templates/web/root_base.html
Forms for category & competition models
=> forms: competitions & category forms

bullet/bullet_admin/templates/bullet_admin/base.html, bullet/bullet_admin/templates/bullet_admin/partials/sidebar_menu.html
=> sidebar: fix scroll with many menu entries

bullet/bullet_admin/templates/bullet_admin/competition/confirm.html, bullet/bullet_admin/templates/bullet_admin/competition/form.html, bullet/bullet_admin/urls.py, bullet/bullet_admin/views/competition.py
Added button to finalize competition to competition edit form.
=> Competition finalizing

bullet/bullet_admin/forms/problem.py, bullet/bullet_admin/templatetags/badmin.py, bullet/bullet_admin/urls.py, bullet/bullet_admin/views/categoryproblems.py
Initial generation of problem and categoryproblem objects
=> Problem generation

bullet/bullet_admin/components.py, bullet/bullet_admin/templates/bullet_admin/components/subheader.html, bullet/bullet_admin/templates/bullet_admin/results/select.html, bullet/bullet_admin/templatetags/badmin.py, bullet/bullet_admin/views/results.py, bullet/problems/views/results.py
- operators can now access results and announcements
- results views in admin now uses new UI
=> Results access for operator

bullet/bullet_admin/components.py, bullet/bullet_admin/fields.py, bullet/bullet_admin/forms/files.py, bullet/bullet_admin/templates/bullet_admin/components/breadcrumb.html, bullet/bullet_admin/templates/bullet_admin/components/breadcrumbs.html, bullet/bullet_admin/templates/bullet_admin/components/empty_state.html, bullet/bullet_admin/templates/bullet_admin/files/tree.html, bullet/bullet_admin/templates/bullet_admin/files/tree_field.html, bullet/bullet_admin/templates/bullet_admin/files/tree_field_open.html, bullet/bullet_admin/templatetags/badmin.py, bullet/bullet_admin/urls/__init__.py, bullet/bullet_admin/urls/files.py, bullet/bullet_admin/views/files.py, bullet/web/templates/form/field.html
=> Admin file browser

bullet/competitions/factories/competition.py, bullet/web/migrations/0009_contentblock_and_more.py, bullet/web/migrations/0017_delete_translation_and_more.py
Should fix problems with migrations introduced in https://github.com/naboj-org/bullet/commit/561d464d87c3b73378bed5ebee38909863eef17a
=> Fix migrations

bullet/bullet/settings.py
=> Fix DjDT without modifying minifier

bullet/bullet_admin/templates/bullet_admin/scanning/problem/_history.html, bullet/bullet_admin/templatetags/badmin.py
=> Highlight category in scanning log

bullet/bullet_admin/templates/bullet_admin/emails/form.html
=> Improve mail campaigns ux

bullet/bullet_admin/forms/documents.py, bullet/bullet_admin/templates/bullet_admin/venues/_layout.html, bullet/bullet_admin/views/venues.py, bullet/documents/generators/tearoff.py
* Enlarge team number in barcode stamp.
* Move barcode below the team number.
* Check page count before generating.
=> Tearoff improvements

bullet/bullet_admin/components.py, bullet/bullet_admin/templates/bullet_admin/components/button.html, bullet/bullet_admin/templates/bullet_admin/components/link.html
- Updated link styles to dynamically change based on type
- Updated button background color when not specified to improve visibility
- Added new styling for button hover effect
=> update-styling-for-buttons-and-links: Update link and button styles

bullet/bullet_admin/templates/bullet_admin/generic/list.html, bullet/bullet_admin/views/__init__.py
=> generic-admin-list-view

bullet/bullet_admin/components.py, bullet/bullet_admin/templates/bullet_admin/components/country.html
Adds a new 'country' component with template to display country name and
flag based on code.
=> add-country-flag-component: Add 'country' component

bullet/bullet_admin/templates/bullet_admin/teams/delete.html, bullet/bullet_admin/views/teams.py
=> Delete team without mail

bullet/bullet_admin/templates/bullet_admin/teams/edit.html, bullet/bullet_admin/templates/bullet_admin/teams/to_competition.html, bullet/bullet_admin/templates/bullet_admin/venues/waiting_list.html, bullet/bullet_admin/templates/bullet_admin/venues/waiting_list_automove.html, bullet/bullet_admin/views/teams.py, bullet/bullet_admin/views/venues.py
=> Waiting list confirmation dialog

bullet/bullet_admin/templates/bullet_admin/teams/edit.html, bullet/bullet_admin/templates/bullet_admin/teams/history.html, bullet/bullet_admin/urls/__init__.py, bullet/bullet_admin/views/teams.py
=> Admin show team history

bullet/bullet_admin/templates/bullet_admin/teams/history.html, bullet/bullet_admin/templates/bullet_admin/teams/revert_team.html, bullet/bullet_admin/urls/__init__.py, bullet/bullet_admin/views/teams.py
=> Admin revert team history

bullet/bullet_admin/templates/bullet_admin/teams/edit.html, bullet/bullet_admin/views/teams.py
=> Admin show team edit link

bullet/bullet_admin/templates/bullet_admin/teams/deleted.html, bullet/bullet_admin/templatetags/badmin.py, bullet/bullet_admin/urls/__init__.py, bullet/bullet_admin/views/teams.py
=> Admin show recently deleted teams

bullet/bullet_admin/templates/bullet_admin/teams/deleted.html, bullet/bullet_admin/templates/bullet_admin/teams/restore.html, bullet/bullet_admin/urls/__init__.py, bullet/bullet_admin/views/teams.py
Restore deleted teams without previous participants
=> Admin restore deleted teams

bullet/bullet_admin/views/__init__.py, bullet/bullet_admin/views/users.py
- **fix-generic-list-country-navigation: constider object might not have country**
- **fix-generic-list-country-navigation: show objects with not-allowed countries if some of them is allowed**
- **fix-generic-list-country-navigation: move unsupported operation from DB to Python**
=> fix generic list country navigation

bullet/web/views/page.py
=> fix: homepage link in pages admin

bullet/bullet_admin/mixins.py
=> fix: redirect to previous page after login

bullet/bullet_admin/templates/bullet_admin/scanning/problem/_scanner.html
=> feat: keep scanning history page between scans

bullet/bullet_admin/views/venues.py
=> feat: allow tex certificates before review
